### PR TITLE
Fix #110 Add instructions for dj-database-url and django-configurations in docs

### LINKED ISSUE #110: Add instructions for django configurations in docs

### PR DESCRIPTION
**Pull request by pauloxnet**

### CODE REVIEW

**Comment by simonw** [comment]
It looks to me like this tip isn't purely specific to `django-configurations` - it should work if you only install `dj-database-url` without installing the rest of `django-configurations`.

I use `dj-database-url` on my Heroku projects without `django-configurations` so I like this pattern a lot.

**Comment by simonw** [comment]
So instead of headlining this session "Django Configurations", I suggest:

### dj-database-url and django-configurations

Plus updated copy to reflect that using either package will enable this configuration pattern.

**Comment by pauloxnet** [comment]
You're totally right. I've updated the code to reflect your comment.

**Comment by simonw** [comment]
Thanks very much!

**Pull request merged**
